# Generated by Django 4.0.3 on 2022-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=0, verbose_name='like'),
        ),
    ]
